### ISSUE TITLE
Priorities?

### ISSUE THREAD

**Issue by dweinstein** [koudelka/honeydew#16]
I'm surveying projects in this space and am curious about how honeydew handles or plans to handle prioritization. What happens when the workers are saturated and an important job comes in that should be run before others in the queue?

thank you for your time/thoughts.

**Comment by koudelka** [comment]
Hey @dweinstein. At the moment, there's no concept of prioritization in Honeydew, but you could simulate it with a separate "high priority" queue, rather than a numeric priority.

That being said, the queue module implementation itself decides which job should be sent to the awaiting worker, so it'd be fairly easy to write, depending on how you want the jobs stored (in memory, in mnesia, in a database, etc).

**Comment by dweinstein** [comment]
thank you!
