### ISSUE TITLE
Infinite timeouts with job_please call

### ISSUE THREAD

**Issue by benwilson512** [koudelka/honeydew#2]
Hey!

I've been looking through the various job queue + worker libraries and I really like what I see here. My primary concern at the moment has to do with the infinite timeout you're using at https://github.com/koudelka/honeydew/blob/master/lib/honeydew/worker.ex#L45 for when a worker is waiting on a job.

While I understand why you're going that route, it's in general best to avoid these. This is particularly true when it blocks a GenServer. The worker process will be unable to respond to any debug or system messages it receives during that time, and its process inbox could fill up indefinitely.

As an alternative, have you considered the general approach taken by the proposed GenRouter architecture? Essentially, each worker would notify either your queue or perhaps an additional Scheduler process that it is available. Then, when a task comes in, the queue would just grab that a pid from its list of available worker pids and send the task off.

I do think there's value to doing it in another process honestly. In that scenario, your queue would also notify the scheduler when a new item arrives, and the scheduler would maintain a count of those items. Then if the count > 0 and a worker says its free, it can match up the job with the worker immediately. In this way you avoid blocking any genservers for an extended period of time.

Thoughts?

**Comment by koudelka** [comment]
Hey @benwilson512,

I think your critique is spot on and that's a change I'd love to make.

I was attempting to emulate a blocking job pull (sort of like a `BRPOP` is redis), thinking that maybe I wouldn't have to track a list of pids, but I ended up instead tracking a list of `call` replies anyways, it seems. At the time, it seemed like a simpler approach.

GenRouter looks wonderful and a great fit for Honeydew. With 1.3 on the horizon, though, I have to wonder if attempting to implement a homebrew version of it would be a bad idea (and probably a waste of time, since I'd trust GenRouter over my own code).

Separating out the queue and scheduler (load balancer?) would be really cool. I'm all about modularity. The current implementation has felt monolithic to me for some time now.

**Comment by koudelka** [comment]
Fixed, see #3.
