### ISSUE TITLE
Cancel job on call timeout

### ISSUE THREAD

**Issue by mfclarke** [koudelka/honeydew#4]
I'd love to be able to kill a job if the cast that creates it times out. I've hacked away at work_queue.ex and kind of got something working but I thought I'd check in here and see if there's an easier non-hacky way.

I'm quite new to Elixir, but I feel like there's some way I can achieve this via process linking maybe?

Thanks for your help!

**Comment by koudelka** [comment]
Hey there. :)

Do you mean `call`? A `cast` will always immediately return `:ok`.

**Comment by mfclarke** [comment]
Yes, sorry I meant call. I've updated the title, thanks!

**Comment by koudelka** [comment]
Hm, well, my worry is that since there may be many reasons for the timeout (no workers available, high latency contacting the queue if it lives on another node, the job failed many times and is being re-queued, very slow job execution), I don't think we can guarantee that the job hasn't been executed when the timeout hits. 

So I believe you'll end up having to categorize your jobs into two kinds: those that must be cancelled before they have a chance to execute, and those that can execute but the caller doesn't end up hearing about it.

If you're looking for something like "don't run this job if the time between the `call` and actual execution start is too long`, that shouldn't be a big deal to wrangle. :)

Can you tell me a bit more about your use case?

**Comment by mfclarke** [comment]
"don't run this job if the time between the call and actual execution start is too long" <- that would work for me!

I have a pipeline that consists of multiple stages that fetch data from different endpoints. Occasionally one of these endpoints can go down for a period of time (I have no control over this), and the jobs can back up. By the time the URL is online again (and jobs start flowing through the workers again) the caller isn't around to receive the data anymore.

What would be really cool is being able to pass an option to ```call``` that tells the worker to simply discard the job if it's "expired" / being executed after the ```call``` timeout. I'm happy to work on this if you want? You just might have to give me a brief outline of how you envision this to function, since I'm pretty new to Elixir :)

And actually just thinking about it, maybe this ```call``` that doesn't throw on timeout is ```call```, but the one that does throw on timeout should be ```call!```?

**Comment by mfclarke** [comment]
@koudelka I just realised I can implement this kind of behaviour without modifying Honeydew, by simply passing an expiry date as a task param and checking this in my worker when work starts. Easy!

**Comment by koudelka** [comment]
@mfclarke Hey, sorry for the delay. You could also send in the pid of the caller with `self` and then use `Process.alive?/1` in the worker to check if the caller has died. Have you seen [elixir-lang/gen_stage](https://github.com/elixir-lang/gen_stage)? It's a demand-driven producer/consumer work pipeline, maybe there's something you can use there too. I'm in the middle of seeing if I can move Honeydew over to it.

If more folks chime in with a desire for the cancel-job-when-caller-dies functionality, I'm happy to add it. :)

**Comment by mfclarke** [comment]
No problem @koudelka. Yes, that could work. The caller is a Phoenix controller, I'll have to check that requests are run in dynamically spawned processes rather than reused. But if so, this would be nicer again. Thanks!

I read about the new gen_stage, but I'm not yet totally confident with GenServer and Supervisors yet. 1 step at a time :)

**Comment by koudelka** [comment]
@mfclarke ah gotcha. feel free to give me a shout if you run into any elixir snags. :)
