### ISSUE TITLE
Delayed Jobs support?

### ISSUE THREAD

**Issue by vovayartsev** [koudelka/honeydew#66]
@koudelka what do you think about adding Delayed Jobs support to honeydew? 

The primary use-case I envision is delayed retries: when a job fail b/o temporary unavailability of some 3-rd party API it makes no sense to retry immediately - that would exhaust all retry attempts too fast.

Would this be a nice feature for honeydew? Maybe it's on the roadmap already?

**Comment by koudelka** [comment]
i think it's a great idea!

implementing it properly might be tricky though, i wouldn't want to jam up the workers by constantly issuing them jobs that aren't ready to run, so the queue would probably have to keep track of when a job should be dispatched.

my guess is that a priority queue would be the weapon of choice here, maybe where the priority threshold is the current time. i'd be nice if we could keep it generalized, but it may have to be a property of the queue implementation itself. (maybe the Queue behaviour could just require that the underlying implementation be a priority queue)

did you have any thoughts about how you'd go about implementing it?

**Comment by vovayartsev** [comment]
> a priority queue would be the weapon of choice here

Totally agree. In theory:

* For in-memory ErlangQueue it should be possible to replace the currently used `:queue` with one of the [implementations](https://github.com/okeuday/pqueue).
* For EctoPollQueue and Honeydew.Queue.Mnesia, it should be possible to add a column which stores priority

> the queue would probably have to keep track of when a job should be dispatched
> maybe the Queue behaviour could just require that the underlying implementation be a priority queue

I like this direction. Right now `Queue.dispatch()` is called in three cases:
* Queue.enqueue()
* Queue.nack()
* Queue.resume()

If I read you right, the plan is to introduce a delayed (via `send_after`?) call to `Queue.dispatch()` in case `module.reserve(private)` returns a job which shouldn't be executed yet. Just need to make sure this implementation doesn't suffer from one of [Falsehoods Programmers beliefs about Time](https://news.ycombinator.com/item?id=4128208)

The open questions which come into my mind:
* how to represent a “delayed” job in the `Job` structure
* where to store time offsets in persistent storages 
* for persistent queues - how to properly migrate the storage so that the existing production setups don’t crash after library version update
* for multi-node setups - would it be possible to upgrade without stopping the queues?
* [long-term] how to implement end-user’s delayed jobs API? Just add another keyword option to `Honeydew.async()`? 

My personal short-term (1-2 months) need is a mnesia-backed job processor with delayed retries. I could dive a spike here and try implementing it the hacky way and later get back to you with my proof-of-concept. My plan is:
* add another field to `Job` structure to hold time offset
* delayed calls to `Queue.dispatch()` call using `send_after` if the job returned from `reserve()` shouldn't run yet
* introduce Honeydew.Queue.DelayedMnesia and Honeydew.FailureMode.DelayedRetry modules

Sounds good?

**Comment by koudelka** [comment]
hey there, i apologize for not getting back to you sooner, lots going on at the moment.

i've been mulling over your response, and the problem as a whole, and i think i have a fairly simple solution for the "single-node" (more on this later) case.

at the moment, the queue is just a list of jobs, operating in FIFO order, executed as fast as possible. adding delayed jobs means that the queue acquires a few additional characteristics:

1. it has to have the ability to insert a job into a place in the queue, according to when it should run.
2. it mustn't execute jobs before they're ready.
3. it has to know how to wake up to dispatch jobs when they're ready.

i believe we can implement those the requirements with pretty minimal complexity, like so:

- jobs would no longer have implicit ordering (FIFO), but be assigned an integer priority indicating when they should run. upon enqueue, the priority would be set by the queue process to the current value of ERTS' monotonic clock.
- the queue wont dispatch jobs if their priority is above the current value of the monotonic clock.
- the queue needs to wake up every once in a while and check to see if there are jobs that need to run

more concretely, for the mnesia queue:

1. `Mnesia.enqueue/2` will need to use the current monotonic clock's value as the job's ID (the sort key).
2. `Mnesia.reserve/1` needs to return the job that's next in line, if it's ready to run (the job with the lowest ID and only if that ID isn't greater than the current value of the monotonic clock)
3. When the `Queue` starts, it should start a one-second timer to send itself a message to wake up and call `Queue.dispatch`, unless the dispatch function has been called within the last second. (busy queues will never fall back to this polling behavior). i'd prefer this over starting and managing timers, i think those may be prone to subtle race conditions.
4. `Mnesia.reset_after_crash/2` will need to reset `id` to the current value of the clock after a crash (mentioned below)


we'll have to make note that folks should run honeydew with [multi-time warp and time correction](http://erlang.org/doc/apps/erts/time_correction.html#multi-time-warp-mode) enabled, so as to ensure that the monotonic clock doesn't freeze.

if a mnesia node crashes, and it's persisting to disk, the monotonic clock values aren't going to have as much meaning when the node comes back up. the values will still tell us the ordering of the jobs, but it wont tell us which jobs should have already executed. i'm ok with just resetting all of the ordering values to the present moment, since honeydew offers at-least-once execution and we encourage people to write idempotent jobs. that'd also have to be in the docs.

----

as for ErlangQueue, it'll have to turn into a priority queue that can handle arbitrary integers as priorities, let's not worry about it for now and just try to get you going with the Mnesia queue. :)

the single-node case also applies to queues where just their data storage layer is replicated (mnesia running on another node replicating honeydew's queue tables, but not running a queue process itself), or queues that are backed by systems that have their own notion of time synchronization (EctoPollQueue). the queue systems that have their own notion of time won't be using ERTS' monotonic clock, they'll handle it themselves (like with `NOW()` in a SQL database).

the truly distributed case (multiple queue process in the cluster) is quite a bit more complex, since time-elapsed would become a matter of opinion between the nodes. i think our two options are to either trust that their clocks are decently synchronized (tut tut), or run a distributed consensus algorithm and disable nodes with unacceptable skew until they agree with the majority.

i think the above answers your first two questions (please tell me if not), to the others:

> for persistent queues - how to properly migrate the storage so that the existing production setups don’t crash after library version update

currently, the mnesia queue just uses an integer for ordering, we'd just be swapping it out with a different integer, same schema, shouldn't be a problem. the crash/restart behavior i mentioned above should properly reset the values when it starts up after upgrading.

> for multi-node setups - would it be possible to upgrade without stopping the queues?

well, this delayed jobs solution is only going to work in the case where only a single queue process is running in the cluster, due to the time skew concerns. it'd definitely be possible to upgrade it without stopping the queue using BEAM's hot code loading upgrade bits, but i suspect that's a bit more trouble than it's worth in this case.

> [long-term] how to implement end-user’s delayed jobs API? Just add another keyword option to Honeydew.async()?

totally, yeah, that sounds good to me dude

-----


i think this solution is pretty low-complexity and should eliminate a lot of edge cases. i hope this all makes sense, please let me know what you think! :)

**Comment by koudelka** [comment]
oh, also, definitely yes to the FailureMode.

 it'd be cool to be able to provide it with delay strategies, maybe like `fixed: seconds`, `exponential: seconds`, etc.

**Comment by alkemisti** [comment]
@vovayartsev , let me know the status of this issue. I'd like to contribute as well.

**Comment by vovayartsev** [comment]
My current progress is here: https://github.com/vovayartsev/honeydew/pull/1/files
@alkemisti @koudelka adding you as collaborators there in case you have some early comments. Especially on the `dispatch_at` part.

I added a single test which schedules a delayed job via `Honeydew.async(job, queue, at: in_1_sec)`, and it passes.

It's definitely not a PR to `koudelka/honeydew` repo yet, because it doesn't match the requirements agreed upon on December 18, and because it's not backward-compatible.

@alkemisti I got blocked by some urgency at my primary job and plan to finish my PR in early March when I have vacations. Please feel free to take over the issue if you're able/willing to move faster (and fork my PR too if you like it).

**Comment by koudelka** [comment]
@vovayartsev hey, just wanted to let you know that i'm working on this. :)

**Comment by vovayartsev** [comment]
@koudelka Hey! Thanks for the update! :-)

In case I'm not too late - I finished my solution in https://github.com/vovayartsev/honeydew/pull/1/files
(well... I could have added more tests and updated the documentation.... but I want to hear your thoughts on the code first)

It adds delayed jobs support to Honeydew API and mnesia queue, and `:fixed_delay_ms` option to the retry strategy. It matches your original thoughts, but:
* I added `uuid4` to the mnesia key, i.e. `{_node, _timestamp, uuid}` - because timestamp is not a stable ID and can't be used e.g. in `cancel` function. There's a migration on startup which ensures smooth `mix deps.update honeydew`
* The actual delay mechanism is a bit different from what you proposed, but if we trace the actual function calls and messages, then the trace is not that much different from a 1-second `send_after` timer checking if there's a task available.

Please let me know if you want me to update the documentation and send a PR to `koudelka/honeydew` repo, or prefer to finish it yourself.

Thanks again for the great project!

**Comment by koudelka** [comment]
hey @vovayartsev / @alkemisti ,

sorry for the lack of communication, i've implemented both delayed jobs and exponential retry in https://github.com/koudelka/honeydew/pull/74 :)

i've made some major changes to how the mnesia queue stores jobs to allow for new features in the future and backwards compatibility, but unfortunately it's not backward compatible with the current version. queues will have to be drained and recreated.

it's on master, give it a spin and let me know what you think. :)

**Comment by koudelka** [comment]
Cut release 1.4.0, [CHANGELOG](https://github.com/koudelka/honeydew/blob/master/CHANGELOG.md#140-2019-4-8).

Holler if you see anything broken. :)
